services:
  api:
    build:
      context: ./backend
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - my-db-volume:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  my-db-volume:

networks:
  app-network:
    driver: bridge
